# Generated by Django 4.2 on 2023-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ManyToManyField(to='onlinecourse.lesson'),
        ),
    ]
